all:
  vars:
    ansible_connection: ssh
    ansible_user: centos
    ansible_become: true
    ansible_ssh_private_key_file: KeyPair_09-08-2020-mumbai.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    security_mode: nonssl

ssl_CA:
  hosts:
    ec2-35-154-24-45.ap-south-1.compute.amazonaws.com:

zookeeper:
  hosts:
    ec2-35-154-24-45.ap-south-1.compute.amazonaws.com:

kafka_broker:
  hosts:
    ec2-13-232-105-222.ap-south-1.compute.amazonaws.com:
    ec2-13-232-169-7.ap-south-1.compute.amazonaws.com:
    ec2-13-127-72-46.ap-south-1.compute.amazonaws.com:

schema_registry:
  hosts:
    ec2-13-232-105-222.ap-south-1.compute.amazonaws.com:

kafka_connect:
  hosts:
    ec2-13-232-169-7.ap-south-1.compute.amazonaws.com:

control_center:
  hosts:
    ec2-13-127-72-46.ap-south-1.compute.amazonaws.com:

elasticsearch:
  hosts:
    ec2-52-66-90-40.ap-south-1.compute.amazonaws.com:

logstash:
  hosts:
    ec2-35-154-241-94.ap-south-1.compute.amazonaws.com:
