all:
  vars:
    ansible_connection: ssh
    ansible_user: centos
    ansible_become: true
    ansible_ssh_private_key_file: KeyPair_nandykarnab_29032020_ap-south-1.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

zookeeper:
  hosts:
    ec2-13-234-112-120.ap-south-1.compute.amazonaws.com:  

kafka_broker:
  hosts:
    ec2-13-233-229-142.ap-south-1.compute.amazonaws.com:
    ec2-35-154-69-219.ap-south-1.compute.amazonaws.com:
    ec2-52-66-208-14.ap-south-1.compute.amazonaws.com:
    
schema_registry:
  hosts:
    ec2-13-233-229-142.ap-south-1.compute.amazonaws.com:

kafka_connect:
  hosts:
    ec2-13-234-112-120.ap-south-1.compute.amazonaws.com:

control_center:
  hosts:
    ec2-13-233-229-142.ap-south-1.compute.amazonaws.com:
