all:
  vars:
    ansible_connection: ssh
    ansible_user: admin
    ansible_become: true
    ansible_ssh_private_key_file: ~/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

zookeeper:
  hosts:
    10.0.1.228:  

kafka_broker:
  hosts:
    10.0.1.240:
    10.0.1.226:
    10.0.1.228:
    
schema_registry:
  hosts:
    10.0.1.226:

kafka_connect:
  hosts:
    10.0.1.226:

control_center:
  hosts:
    10.0.1.228:
