all:
  vars:
    ansible_connection: ssh
    ansible_user: centos
    ansible_become: true
    ansible_ssh_private_key_file: ~/KeyPair.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

zookeeper:
  hosts:
    ec2-13-233-163-147.ap-south-1.compute.amazonaws.com:  
    # Zookeeper Hostname/IP
    # e.g. 192.168.0.192:
    #         OR
    # e.g. zookeeper-1.example.com:

kafka_broker:
  hosts:
    ec2-13-233-151-153.ap-south-1.compute.amazonaws.com:
    ec2-52-66-237-215.ap-south-1.compute.amazonaws.com:
    ec2-13-233-131-22.ap-south-1.compute.amazonaws.com:
    # Kafka Broker Hostname/IP
    # e.g. 192.168.0.192:
    #         OR
    # e.g. kafka-boker-1.example.com:

schema_registry:
  hosts:
    # Schema Registry Hostname/IP
    # e.g. 192.168.0.192:
    #         OR
    # e.g. kafka-boker-1.example.com:
