all:
  vars:
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_become: true
    ansible_ssh_private_key_file: ~/KeyPair.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

zookeeper:
  hosts:
    ec2-15-206-209-100.ap-south-1.compute.amazonaws.com:  

kafka_broker:
  hosts:
    ec2-15-206-209-100.ap-south-1.compute.amazonaws.com:

schema_registry:
  hosts:
    ec2-15-206-209-100.ap-south-1.compute.amazonaws.com: