all:
  vars:
    ansible_connection: ssh
    ansible_user: admin
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

zookeeper:
  hosts:
    10.0.1.240:  

kafka_broker:
  hosts:
    10.0.1.240:

schema_registry:
  hosts:
    10.0.1.240:
