all:
  vars:
    ansible_connection: ssh
    ansible_user: admin
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

zookeeper:
  hosts:
    <zookeeper_hosts>:  

kafka_broker:
  hosts:
    <Broker 1>:
    <Broker 2>:
    <Broker 3>8:
    
schema_registry:
  hosts:
    <Schema_Registry>:

kafka_connect:
  hosts:
    <Kafka_Connect>:

control_center:
  hosts:
    10.0.1.228:
