all:
  vars:
    ansible_connection: ssh
    ansible_user: <ssh_user>
    ansible_become: true
    ansible_ssh_private_key_file: <private_key>
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

zookeeper:
  hosts:
    # Zookeeper Hostname/IP
    # e.g. 192.168.0.192:
    #         OR
    # e.g. zookeeper-1.example.com:

kafka_broker:
  hosts:
    # Kafka Broker Hostname/IP
    # e.g. 192.168.0.192:
    #         OR
    # e.g. kafka-boker-1.example.com:

schema_registry:
  hosts:
    # Schema Registry Hostname/IP
    # e.g. 192.168.0.192:
    #         OR
    # e.g. kafka-boker-1.example.com: