all:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_become: true
    ansible_ssh_private_key_file: ~/KeyPair.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

zookeeper:
  hosts:
    ec2-3-7-69-70.ap-south-1.compute.amazonaws.com:  

kafka_broker:
  hosts:
    ec2-35-154-70-169.ap-south-1.compute.amazonaws.com:
    ec2-13-233-147-138.ap-south-1.compute.amazonaws.com:
    ec2-52-66-240-92.ap-south-1.compute.amazonaws.com:

# schema_registry:
#   hosts:
#     # Schema Registry Hostname/IP
#     # e.g. 192.168.0.192:
#     #         OR
#     # e.g. kafka-boker-1.example.com:
