kafka_user: cp-kafka
kafka_group: confluent
zookeeper_service_name: confluent-zookeeper
kafka_broker_service_name: confluent-server
control_center_service_name: confluent-control-center
kafka_connect_service_name: confluent-kafka-connect
kafka:
  kafka_broker_port: 9092
  kafka_connect_port: 8083
  schema_registry_port: 8081
  properties:
    zookeeper_client_port: 2181
